spring.application.name=demo
spring.datasource.url=jdbc:sqlite:database/app.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.sql.init.platform=sqlite
spring.sql.init.mode=always
spring.sql.init.platform=sqlite
